name: Python Application

on: 
  push:
    branches:
      - main  # Change this to your target branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin  # Install the Firebase Admin SDK

    - name: Run sendemail.py
      run: python sendemail.py  # Run your Python script
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}  # Set your Firebase service account key
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}  # Set your sender email
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}  # Set your sender email password
